# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-scrnaseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - bioconda::multiqc=1.7
  - matplotlib=3.0.3        # Current 3.1.0 build incompatible with multiqc=1.7
  - bioconda::salmon=0.14.1
  - bioconda::r-seurat=3.0.1
  - bioconda::bioconductor-isee=1.2.0
  - bioconda::bioconductor-tximeta=1.0.3
  - conda-forge::r-markdown=1.0
  - bioconda::bioawk=1.0
  - bioconda::bioconductor-alevinqc=1.0.0
  - bioconda::bioconductor-tximport=1.12.3
  - bioconda::star=2.7.1a
  - samtools=1.9
  - gffread=0.11.4
  - bioconda::kallisto=0.46.0
  - bioconda::bustools=0.39.2