# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-scrnaseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::python
  - bioconda::multiqc
  - bioconda::salmon
  - bioconda::r-seurat
  - bioconda::bioconductor-isee
  - bioconda::bioconductor-tximeta
  - conda-forge::r-markdown
  - bioconda::bioawk
  - bioconda::star=2.7.1a
  - samtools=1.9
  - gffread=0.11.4
